spring:
  profiles:
    include:
      - googlemail
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092 #,localhost:9094,localhost:9095
    my:
      push:
        topic:
          name: test
          group: test-push-group

server:
  port: 8082